wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import logging

from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect
from wikiDB.DatabaseModel import Page
import re
import doctest

doctest.testmod()
log = logging.getLogger('wiki')
bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get_from_DB('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_from_DB(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        page.load(form)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        log.info(f'Successfully saved page \'{page.title}\'')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    if(url=='home'):
        flash('Can\'t move the home page!')
        return display('home')
    page = current_wiki.get_from_DB(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        log.info(f'Moving page \'{url}\' to \'{newurl}\'')
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_from_DB(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    log.info(f'Page \'{page.title}\' was successfully deleted')
    return redirect(url_for('wiki.home'))


# Replaced by categories page
@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/categories/')
@protect
def categories():
    tags = current_wiki.get_tags()
    page = current_wiki.index()
    pages = []
    for item in page:
        pageTags = (item.tags).split(',')
        if item.tags == '':
            pages.append([[item.title,item.url],"Uncategorized"])
        else:
            pages.append([[item.title,item.url],[pageTags]])
    #   BACKUP IN CASE DATABASE SWITCH MESSES WITH FUNCTIONS ABOVE
    #   POSSIBLY PASS [[[PAGE.NAME,PAGE.URL],CATEGORY],[PAGE,CATEGORY]] LIST CREATED BEFORE PASSING TO HTML
    #   IF QUERIES CAN'T BE DONE IN HTML
    #   tags = TagTable.select(name=True).exec()
    #   pages = PageTable.select(title=True).exec()
    #   relations = [tagid,pageid]
    #   for (tag in tags){
    #       print(tag.name)
    #       for (relationship in relationships){
    #           if tag.id = relationship[0]{
    #               page = PageTable.tables(PageID = relationship[1])
    #               <a href=(page.url)>page.name</a>
    #           }
    #       }
    #   }
    return render_template('categories.html', pages=pages, tags=tags)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    """
    Defines a route to display the search page or the search
    page with its results based on the search terms given by the user.
    @return: Render template for search page
    """
    form = SearchForm()
    if form.validate_on_submit():
        searchText = form.term.data
        log.debug(f'Raw search text: \'{searchText}\'')
        caseInsensitive = form.ignore_case.data
        option = form.option.data

        results = query_for_regex(option, searchText, caseInsensitive)
        if not caseInsensitive:
            if not results:
                term = format_term(searchText)
                words = term[1:-1].split('%')
                idList = []
                searchTerm = term.encode()
                log.debug(f'Processed search text: \'{searchTerm}\'')
                results = Page.query.filter(Page.content.like(searchTerm) | Page.title.like(searchTerm)).all()
                for result in results:
                    if all((word.encode() in result.content for word in words) or (word.encode() in result.title
                           for word in words)):
                        idList.append(result.id)
                results = iterate_id_list(option, idList)
        else:
            if not results:
                term = format_term(searchText)
                searchTerm = term.encode()
                log.debug(f'Processed search text: \'{searchTerm}\'')
                results = query_for_search(option, searchTerm)

        return render_template('search.html', form=form, results=results, search=form.term.data,
                               case=form.ignore_case.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data.strip())
        login_user(user)
        user.set('authenticated', True)
        log.info(f'User \'{form.name.data}\' has logged on')
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    log.info(f'User has logged out')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


def query_for_search(option, search_term):
    """
    Returns pages that match the term or terms that was given by the user.
    @param option: sort by option for pages
    @param search_term: term or terms given by the user to search
    @return: a list of all the pages that matches the term or terms given
    """
    log.info(f'Searching for pages with criteria: \'{search_term}\', option: \'{option}\'')

    results = None
    if option == "default":
        results = Page.query.filter(Page.content.like(search_term) | Page.title.like(search_term)).all()
    elif option == "CDO":
        results = Page.query.filter(Page.content.like(search_term) | Page.title.like(search_term)) \
            .order_by(Page.date_created).all()
    elif option == "CDN":
        results = Page.query.filter(Page.content.like(search_term) | Page.title.like(search_term)) \
            .order_by(Page.date_created.desc()).all()
    elif option == "EDO":
        results = Page.query.filter(Page.content.like(search_term) | Page.title.like(search_term)) \
            .order_by(Page.last_edited).all()
    elif option == "EDN":
        results = Page.query.filter(Page.content.like(search_term) | Page.title.like(search_term)) \
            .order_by(Page.last_edited.desc()).all()
    return results


def query_for_regex(option, search_term, case_insensitive):
    """
    Returns articles that match the regex that was given by the user.
    @param option: sort by option for articles
    @param search_term: regex given by the user to search
    @param case_insensitive: a boolean that determines if the search is case-sensitive or not
    @return: a list of all the articles that matches the regex given
    """
    log.info(f'Searching for pages with criteria: \'{search_term}\', option: \'{option}\'')

    regexIdList = []
    queryResults = Page.query.all()
    special_characters = "\"!@#\\$%^&*()-+?_=,<>/\""
    if not case_insensitive:
        for result in queryResults:
            content = result.content.decode()
            title = result.title
            if not content[0].isalnum() and not content[0] in special_characters:
                content = content[1:-1]
            if re.search(search_term, content) or re.search(search_term, title):
                regexIdList.append(result.id)
    else:
        for result in queryResults:
            content = result.content.decode()
            title = result.title
            if not content[0].isalnum() and not content[0] in special_characters:
                content = content[1:-1]

wiki/web/templates/base.html
<!--
 Isaiah Snapp
 Responsible for CSS and overall usability for the site.
 You will see some span headers within this file and other html files.
 These span headers include the text color and the font type.
 I realize something that I could've done better would be to write a span class
 in the bootstrap.css file so that it could be used universally through the HTML pages.
 I also created a CSS file called backgroundcolor.css which allowed me to add specific
 colored backgrounds to different aspects of the webpages. For example, we have the
 index page which has a white background around it, so it could be differentiated from
 the actual background color. Something else I had to make sure all the different pages being added
 had the correct color with the markdown page as well we have the ability for when a different
 page with a different title will continue to stay the same color no matter what the text says.
 The things that I have changed has been able to be very versatile with many features that
 we have added including the preview ability on the categories page.
 So basically in conclusion here is a list of things that I have done:
 - Added a CSS page for changing the background color of the website (color listed below)
 - Changed background color to #1f6377
 - Changed text color to #ff8c00
 - Changed the font to JetBrains Mono ExtraBold
 - Made sure that all the text color was the same throughout the site as to keep consistency
 - Added the ability to change text color of the main content of an article to the main web pages text color
 - Added a white background to some tables as to show a difference in the background color such as in the index page
 - Added vertical dividers between the navigation bar buttons to show space and a more filling sense to the bar
 - Changed text color of navigation buttons as well as the Add, Move, Edit, Delete buttons to the sites main color
 - Made sure the text color in the preview was presenting with color as the actual page
 - Changed it so that the text color of the search page with the results correctly displays
 Changes that could be improvements:
    - Set the text color and the font in the css page so it could be used universally when new pages are added
    - Removing the home page's delete button
    - Adding an ability to insert images into a new page when a user creates one
    - Hovering over page title gives a brief description of a page
 -->
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='backgroundcolor.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
                                <li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.home') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Home</span></a></li>
                                <li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.index') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Index</span></a></li>
                                <li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.categories') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Categories</span></a></li>
                                <li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.search') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Search</span></a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">New Page</span></a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								{% if current_user.is_anonymous %}
                                    <li><a href="{{ url_for('wiki.user_login') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Login</span></a></li>
								{% else %}
                                    <li><a href="{{ url_for('wiki.user_logout') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Logout</span></a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
                            <h1>{% block title %}<span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ page.title }}</span>{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
                        <div class="alert alert-error"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Errors occured verifying your input. Please check the marked fields below.</span></div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/editor.html
<!--
 Isaiah Snapp
 Responsible for CSS and overall usability for the site.
 You will see some span headers within this file and other html files.
 These span headers include the text color and the font type.
 I realize something that I could've done better would be to write a span class
 in the bootstrap.css file so that it could be used universally through the HTML pages.
 I also created a CSS file called backgroundcolor.css which allowed me to add specific
 colored backgrounds to different aspects of the webpages. For example, we have the
 index page which has a white background around it, so it could be differentiated from
 the actual background color. Something else I had to make sure all the different pages being added
 had the correct color with the markdown page as well we have the ability for when a different
 page with a different title will continue to stay the same color no matter what the text says.
 The things that I have changed has been able to be very versatile with many features that
 we have added including the preview ability on the categories page.
 So basically in conclusion here is a list of things that I have done:
 - Added a CSS page for changing the background color of the website (color listed below)
 - Changed background color to #1f6377
 - Changed text color to #ff8c00
 - Changed the font to JetBrains Mono ExtraBold
 - Made sure that all the text color was the same throughout the site as to keep consistency
 - Added the ability to change text color of the main content of an article to the main web pages text color
 - Added a white background to some tables as to show a difference in the background color such as in the index page
 - Added vertical dividers between the navigation bar buttons to show space and a more filling sense to the bar
 - Changed text color of navigation buttons as well as the Add, Move, Edit, Delete buttons to the sites main color
 - Made sure the text color in the preview was presenting with color as the actual page
 - Changed it so that the text color of the search page with the results correctly displays
 Changes that could be improvements:
    - Set the text color and the font in the css page so it could be used universally when new pages are added
    - Removing the home page's delete button
    - Adding an ability to insert images into a new page when a user creates one
    - Hovering over page title gives a brief description of a page
 -->
{% extends "base.html" %}

{% block title -%}
    <span style="color: #ff8c00; ">Wiki Editor</span>
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
    <li class="active"><a href="#editor" data-toggle="tab"><span style="color: #ff8c00; ">Editor</span></a></li>
    <li><a href="#preview" data-toggle="tab" id="previewlink"><span style="color: #ff8c00; ">Preview</span></a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
			{{ input(form.body, placeholder="Markdown", class="span7", rows="20") }}
			{{ input(form.tags, placeholder="Category & Tags ([Category|Tag] seperated by commas)", class="span7", autocomplete="off") }}
			<div class="form-actions">
        <div class="pull-left">
            <a class="btn" href="#preview" id="previewbtn">Preview</a>
        </div>
				<div class="pull-right">
                    <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
                    <button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

{% block sidebar %}
    <h3><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Editor How-To</span></h3>
    <p><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</span></p>
<pre><code><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">* I
* am
* a
* list</span></code></pre>
    <span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Turns into:</span>
<ul><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</span></ul>
<span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' "><p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
    <p>Headers are as follows:</p></span>
<span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' "><pre><code># Level 1
## Level 2
### Level 3</code></pre></span>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}
$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Loading...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

wiki/web/templates/index.html
<!--
 Isaiah Snapp
 Responsible for CSS and overall usability for the site.
 You will see some span headers within this file and other html files.
 These span headers include the text color and the font type.
 I realize something that I could've done better would be to write a span class
 in the bootstrap.css file so that it could be used universally through the HTML pages.
 I also created a CSS file called backgroundcolor.css which allowed me to add specific
 colored backgrounds to different aspects of the webpages. For example, we have the
 index page which has a white background around it, so it could be differentiated from
 the actual background color. Something else I had to make sure all the different pages being added
 had the correct color with the markdown page as well we have the ability for when a different
 page with a different title will continue to stay the same color no matter what the text says.
 The things that I have changed has been able to be very versatile with many features that
 we have added including the preview ability on the categories page.
 So basically in conclusion here is a list of things that I have done:
 - Added a CSS page for changing the background color of the website (color listed below)
 - Changed background color to #1f6377
 - Changed text color to #ff8c00
 - Changed the font to JetBrains Mono ExtraBold
 - Made sure that all the text color was the same throughout the site as to keep consistency
 - Added the ability to change text color of the main content of an article to the main web pages text color
 - Added a white background to some tables as to show a difference in the background color such as in the index page
 - Added vertical dividers between the navigation bar buttons to show space and a more filling sense to the bar
 - Changed text color of navigation buttons as well as the Add, Move, Edit, Delete buttons to the sites main color
 - Made sure the text color in the preview was presenting with color as the actual page
 - Changed it so that the text color of the search page with the results correctly displays
 Changes that could be improvements:
    - Set the text color and the font in the css page so it could be used universally when new pages are added
    - Removing the home page's delete button
    - Adding an ability to insert images into a new page when a user creates one
    - Hovering over page title gives a brief description of a page
 -->
{% extends "base.html" %}

{% block title %}<span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Page Index</span>{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr class = "backgroundText">
                <th><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Title</span></th>
                <th><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">URL</span></th>
			</tr>
		</thead>
		<tbody class = "backgroundText">
			{% for page in pages %}
				<tr>
                    <td><a href="{{ url_for('wiki.display', url=page.url) }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ page.title }}</span></a></td>
                    <td><a href="{{ url_for('wiki.display', url=page.url) }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ page.url }}</span></a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
    <p class = "backgroundText"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">There are no pages yet.</span></p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
    <li><a href="{{ url_for('wiki.create') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">New Page</span></a></li>
    <li><a href="{{ url_for('wiki.categories') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Categories</span></a></li>
    <li><a href="{{ url_for('wiki.search') }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Search</span></a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/page.html
<!--
 Isaiah Snapp
 Responsible for CSS and overall usability for the site.
 You will see some span headers within this file and other html files.
 These span headers include the text color and the font type.
 I realize something that I could've done better would be to write a span class
 in the bootstrap.css file so that it could be used universally through the HTML pages.
 I also created a CSS file called backgroundcolor.css which allowed me to add specific
 colored backgrounds to different aspects of the webpages. For example, we have the
 index page which has a white background around it, so it could be differentiated from
 the actual background color. Something else I had to make sure all the different pages being added
 had the correct color with the markdown page as well we have the ability for when a different
 page with a different title will continue to stay the same color no matter what the text says.
 The things that I have changed has been able to be very versatile with many features that
 we have added including the preview ability on the categories page.
 So basically in conclusion here is a list of things that I have done:
 - Added a CSS page for changing the background color of the website (color listed below)
 - Changed background color to #1f6377
 - Changed text color to #ff8c00
 - Changed the font to JetBrains Mono ExtraBold
 - Made sure that all the text color was the same throughout the site as to keep consistency
 - Added the ability to change text color of the main content of an article to the main web pages text color
 - Added a white background to some tables as to show a difference in the background color such as in the index page
 - Added vertical dividers between the navigation bar buttons to show space and a more filling sense to the bar
 - Changed text color of navigation buttons as well as the Add, Move, Edit, Delete buttons to the sites main color
 - Made sure the text color in the preview was presenting with color as the actual page
 - Changed it so that the text color of the search page with the results correctly displays
 Changes that could be improvements:
    - Set the text color and the font in the css page so it could be used universally when new pages are added
    - Removing the home page's delete button
    - Adding an ability to insert images into a new page when a user creates one
    - Hovering over page title gives a brief description of a page
 -->
{% extends "base.html" %}

{% block title %}
    <span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ page.title }}</span>
{% endblock title %}

{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
        <h3><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Are you sure?</span></h3>
    </div>
    <div class="modal-body">
        <span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' "><p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p></span>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
        <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Yes, delete.</span></a>
    </div>
  </div>
    <span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ page }}</span>
{% endblock content %}

{% block sidebar %}
{% if page.tags %}
    <h3><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Tags</span></h3>
  <ul>
      {% for tag in page.tags.split(',') %}
          <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">{{ tag|trim }}</span></a></li>
      {% endfor %}
  </ul>
{% endif %}
    <h3><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Actions</span></h3>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="{{ url_for('wiki.edit', url=page.url) }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Edit</span></a></li>
    <li><a href="{{ url_for('wiki.move', url=page.url) }}"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Move</span></a></li>
    <li><a href="#confirmDelete" data-toggle="modal" class="text-error"><span style="color: #ff8c00; font-family: 'JetBrains Mono ExtraBold' ">Delete</span></a></li>
</ul>
{% endblock sidebar %}